return {
    {"nvim-lua/plenary.nvim"},
    {"christoomey/vim-tmux-navigator"},
    {"szw/vim-maximizer"},
    {"tpope/vim-surround"},
    {"vim-scripts/ReplaceWithRegister"},
    {"numToStr/Comment.nvim"},
    {"nvim-tree/nvim-tree.lua"},
    {"kyazdani42/nvim-web-devicons"},
    {"nvim-lualine/lualine.nvim"},
    {"nvim-telescope/telescope-fzf-native.nvim", build = "make" },
    {"nvim-telescope/telescope.nvim"},
    {"hrsh7th/nvim-cmp"},
    {"hrsh7th/cmp-buffer"},
    {"L3MON4D3/LuaSnip"},
    {"saadparwaiz1/cmp_luasnip"},
    {"rafamadriz/friendly-snippets"},
    {"williamboman/mason.nvim"},
    {"williamboman/mason-lspconfig.nvim"},
    {"neovim/nvim-lspconfig"},
    {"udalov/kotlin-vim"},
    {"hrsh7th/cmp-nvim-lsp"},
    {"glepnir/lspsaga.nvim"},
    {"onsails/lspkind.nvim"},
    {"jose-elias-alvarez/null-ls.nvim"},
    {"jayp0521/mason-null-ls.nvim"},
    {"windwp/nvim-autopairs"},
    {"windwp/nvim-ts-autotag"},
    {"lewis6991/gitsigns.nvim"},
    {"folke/todo-comments.nvim", dependencies = {"nvim-lua/plenary.nvim"}, opts = {} },
    {"ryanoasis/vim-devicons"},
    {"ThePrimeagen/harpoon", branch = "harpoon2", dependencies = {"nvim-lua/plenary.nvim"}},
    {"nvim-treesitter/nvim-treesitter", build =  ":TSUpdate", opts = {indent = {enable = true},} },
    {"tjdevries/colorbuddy.nvim"},
    {"nvimdev/dashboard-nvim", event = 'VimEnter', config = function() require('dashboard').setup{} end, },
    { "lervag/vimtex", lazy = false, init = function() vim.g.vimtex_view_method = "zathura" end }
}
